schemes:
  - https
swagger: "2.0"
info:
  title: Company Package APi
  version: 1.0.0
  description: API endpoints for Company Package
  x-ibm-name: Company-Package-APi
servers:
  - url: https://tm-https-tcam.apps.6808c3526d9f36b0be0adf9a.ap1.techzone.ibm.com
    description: Public domain server
paths:
  /company:
    get:
      summary: Company IBM
      description: GET method for /company endpoint
      operationId: getCompanyIBM
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - system
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
