swagger: "2.0"
info:
  title: Company Package API Test
  version: 1.0.0
  description: API endpoints for Company Package Test
  x-ibm-name: Company-Package-API-Test
schemes:
  - https
host: tibco-ibm-service-tibco-bwce.apps.6808c3526d9f36b0be0adf9a.ap1.techzone.ibm.com
basePath: /
paths:
  /company:
    get:
      summary: Get Company IBM
      description: Retrieve company data from IBM system
      operationId: getCompanyIBM
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - System
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error
