swagger: "2.0"
info:
  title: Company Package API Test
  version: 1.0.0
  description: API endpoints for Company Package Test
  x-ibm-name: Company-Package-API-Test
schemes:
  - https
  - http
paths:
  /company:
    get:
      summary: Get Company IBM
      description: Retrieve company data from IBM system
      operationId: getCompanyIBM
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Post Company IBM
      description: POST method for /company endpoint
      operationId: postCompanyIBM
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error
x-ibm-configuration:
  properties:
    target-url:
      value: >-
        http://tibco-ibm-service-tibco-bwce.apps.6808c3526d9f36b0be0adf9a.ap1.techzone.ibm.com:80/company
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  application-authentication-source:
    - header
