swagger: "2.0"
info:
  title: Swagger Petstore API Test
  version: 1.0.0
  description: API endpoints for Swagger Petstore Test
schemes:
  - https
  - http
paths:
  /v2/pet/findByStatus:
    get:
      summary: Get Petstore
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Post Petstore
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            additionalProperties:
              type: string
        "400":
          description: Bad request
        "500":
          description: Internal server error

x-ibm-configuration:
  properties:
    target-url:
      value: >-
        https://petstore.swagger.io/v2/pet/findByStatus
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  application-authentication-source:
    - header
